"""add shared_chats table

Revision ID: 6c8654bafbaf
Revises: b2be60ac619f
Create Date: 2025-09-21 12:32:22.511014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8654bafbaf'
down_revision: Union[str, Sequence[str], None] = 'b2be60ac619f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('share_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_chats_id'), 'shared_chats', ['id'], unique=False)
    op.create_index(op.f('ix_shared_chats_share_code'), 'shared_chats', ['share_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_chats_share_code'), table_name='shared_chats')
    op.drop_index(op.f('ix_shared_chats_id'), table_name='shared_chats')
    op.drop_table('shared_chats')
    # ### end Alembic commands ###
