"""model filemetadata updated

Revision ID: c09fe1b6cab6
Revises: 9e719a5e464b
Create Date: 2025-09-09 15:05:03.814818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09fe1b6cab6'
down_revision: Union[str, Sequence[str], None] = '9e719a5e464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('table_names', sa.JSON(), nullable=True))
    op.add_column('file_metadata', sa.Column('columns', sa.JSON(), nullable=True))
    op.add_column('file_metadata', sa.Column('num_rows', sa.Integer(), nullable=True))
    op.add_column('file_metadata', sa.Column('num_columns', sa.Integer(), nullable=True))
    op.add_column('file_metadata', sa.Column('summary_stats', sa.JSON(), nullable=True))
    op.add_column('file_metadata', sa.Column('bucket_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'bucket_path')
    op.drop_column('file_metadata', 'summary_stats')
    op.drop_column('file_metadata', 'num_columns')
    op.drop_column('file_metadata', 'num_rows')
    op.drop_column('file_metadata', 'columns')
    op.drop_column('file_metadata', 'table_names')
    # ### end Alembic commands ###
