"""create shared_dashboards and activity_logs

Revision ID: e5d7eeda8ec9
Revises: f0de352f4a07
Create Date: 2025-09-17 09:10:25.010245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d7eeda8ec9'
down_revision: Union[str, Sequence[str], None] = 'f0de352f4a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
