"""models updated

Revision ID: e8b9dab4acc9
Revises: 
Create Date: 2025-10-07 12:03:54.342668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b9dab4acc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('is_active', sa.Integer(), nullable=False,server_default='1'))
    op.add_column('file_metadata', sa.Column('is_active', sa.Integer(), nullable=False,server_default='1'))
    op.add_column('messages', sa.Column('is_active', sa.Integer(), nullable=False,server_default='1'))
    op.add_column('shared_chats', sa.Column('is_active', sa.Integer(), nullable=False,server_default='1'))
    op.add_column('shared_dashboards', sa.Column('is_active', sa.Integer(), nullable=False,server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_dashboards', 'is_active')
    op.drop_column('shared_chats', 'is_active')
    op.drop_column('messages', 'is_active')
    op.drop_column('file_metadata', 'is_active')
    op.drop_column('dashboards', 'is_active')
    # ### end Alembic commands ###
